version: '3'
services:
  server:
    container_name: news-server
    restart: always
    build: ./news-server
    ports:
      - "80:3000"
    links: 
      - db
  db:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"