version: '3'
services:
  news-client:
    restart: always
    build: ./news-client
    ports:
      - "80:3000"
    depends_on:
      - news-server
  news-server:
    restart: always
    build: ./news-server
    ports:
      - "3005:3005"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"